[package]
name = "rust-xcstrings"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9.4", features = ["v4_10"] }
open = "5.3.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"